-- MySQL Script generated by MySQL Workbench
-- jeu. 20 juil. 2017 13:21:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id`         INT(11)     NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name`  VARCHAR(25) NOT NULL,
  `gender`     VARCHAR(25) NOT NULL,
  `email`      VARCHAR(40) NOT NULL,
  `username`   VARCHAR(25) NOT NULL,
  `password`   VARCHAR(25) NOT NULL,
  `is_teacher` TINYINT(1)  NOT NULL DEFAULT 0,
  `status`     INT         NOT NULL DEFAULT 0,
  `role`       VARCHAR(10) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centers` ;

CREATE TABLE IF NOT EXISTS `centers` (
  `id`      INT(11)     NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(25) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `zip`     VARCHAR(25) NOT NULL,
  `city`    VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promotions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promotions` ;

CREATE TABLE IF NOT EXISTS `promotions` (
  `id`          INT(11) NOT  NULL     AUTO_INCREMENT,
  `name`        VARCHAR(45)  NOT NULL,
  `description` VARCHAR(255) NULL,
  `start_date`  DATE         NULL     DEFAULT NULL,
  `end_date`    DATE         NULL     DEFAULT NULL,
  `center_id`   INT          NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_promotions_center_id` (`center_id` ASC),
  CONSTRAINT `FK_promotions_center_id`
    FOREIGN KEY (`center_id`)
    REFERENCES `centers` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rooms` ;

CREATE TABLE IF NOT EXISTS `rooms` (
  `id`        INT(11)     NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(25) NOT NULL,
  `nb_seats`  INT         NOT NULL DEFAULT 0,
  `center_id` INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_rooms_center_id` (`center_id` ASC),
  CONSTRAINT `FK_rooms_center_id`
    FOREIGN KEY (`center_id`)
    REFERENCES `centers` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skills` ;

CREATE TABLE IF NOT EXISTS `skills` (
  `id`          INT(11)      NOT NULL AUTO_INCREMENT,
  `name`        VARCHAR(25)  NOT NULL,
  `description` VARCHAR(255) NULL     DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lessons` ;

CREATE TABLE IF NOT EXISTS `lessons` (
  `id`           INT(11)      NOT NULL AUTO_INCREMENT,
  `start_time`   DATETIME NOT NULL,
  `end_time`     DATETIME NOT NULL,
  `note`         VARCHAR(255) NULL     DEFAULT NULL,
  `user_id`      INT          NOT NULL,
  `promotion_id` INT          NULL,
  `room_id`      INT          NULL,
  `skill_id`     INT          NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_lessons_user_id` (`user_id` ASC),
  INDEX `FK_lessons_promotion_id` (`promotion_id` ASC),
  INDEX `FK_lessons_room_id` (`room_id` ASC),
  INDEX `FK_lessons_skill_id` (`skill_id` ASC),
  CONSTRAINT `FK_lessons_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`),
  CONSTRAINT `FK_lessons_promotion_id`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `promotions` (`id`),
  CONSTRAINT `FK_lessons_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `rooms` (`id`),
  CONSTRAINT `FK_lessons_skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `skills` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todolists` ;

CREATE TABLE IF NOT EXISTS `todolists` (
  `id`      INT(11)     NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(30) NOT NULL,
  `user_id` INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_todolists_user_id` (`user_id` ASC),
  CONSTRAINT `FK_todolists_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks` ;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id`                INT(11)      NOT NULL AUTO_INCREMENT,
  `name`              VARCHAR(255) NOT NULL,
  `description`       TEXT         NULL     DEFAULT NULL,
  `status`            INT          NOT NULL,
  `start_date`        DATETIME     NULL     DEFAULT NULL,
  `due_date`          DATETIME     NULL     DEFAULT NULL,
  `end_date`          DATETIME     NULL     DEFAULT NULL,
  `creation_date`     DATETIME     NOT NULL,
  `modification_date` DATETIME     NOT NULL,
  `todolist_id`       INT          NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_tasks_todolist_id` (`todolist_id` ASC),
  CONSTRAINT `FK_tasks_todolist_id`
    FOREIGN KEY (`todolist_id`)
    REFERENCES `todolists` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `presences` ;

CREATE TABLE IF NOT EXISTS `presences` (
  `id`         INT(11)      NOT NULL AUTO_INCREMENT,
  `is_present` TINYINT(1)   NOT NULL DEFAULT 0,
  `excuse`     VARCHAR(255) NULL     DEFAULT NULL,
  `lesson_id`  INT(11)      NOT NULL,
  `user_id`    INT(11)      NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_presences_lesson_id` (`lesson_id` ASC),
  INDEX `fk_presences_users1_idx` (`user_id` ASC),
  CONSTRAINT `FK_presences_lesson_id`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `lessons` (`id`),
  CONSTRAINT `fk_presences_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_skills` ;

CREATE TABLE IF NOT EXISTS `users_skills` (
  `id`       INT NOT NULL AUTO_INCREMENT,
  `level`    INT NOT NULL,
  `user_id`  INT NOT NULL,
  `skill_id` INT NOT NULL,
  INDEX `FK_has_someskill_skill_id` (`skill_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_has_someskill_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`),
  CONSTRAINT `FK_has_someskill_skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `skills` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_centers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_centers` ;

CREATE TABLE IF NOT EXISTS `users_centers` (
  `id`        INT NOT NULL AUTO_INCREMENT,
  `user_id`   INT NOT NULL,
  `center_id` INT NOT NULL,
  INDEX `FK_works_into_center_id` (`center_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_works_in_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`),
  CONSTRAINT `FK_works_into_center_id`
    FOREIGN KEY (`center_id`)
    REFERENCES `centers` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_teach_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_teach_skills` ;

CREATE TABLE IF NOT EXISTS `users_teach_skills` (
  `id`       INT NOT NULL AUTO_INCREMENT,
  `level`    INT NULL     DEFAULT NULL,
  `user_id`  INT NOT NULL,
  `skill_id` INT NOT NULL,
  INDEX `FK_can_teach_skill_id` (`skill_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_can_teach_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_can_teach_skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `skills` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_promotions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_promotions` ;

CREATE TABLE IF NOT EXISTS `users_promotions` (
  `id`           INT     NOT NULL AUTO_INCREMENT,
  `user_id`      INT(11) NOT NULL,
  `promotion_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_promotions_promotions1_idx` (`promotion_id` ASC),
  INDEX `fk_users_has_promotions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_promotions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_promotions_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
